model_100k_300_10_10_1:
  corpus_size: 100000
  embedding_size: 300
  context_window: 10
  epochs: 10
  min_count: 1

model_10k_300_8_25_1:
  corpus_size: 10000
  embedding_size: 300
  context_window: 8
  epochs: 25
  min_count: 1

model_50k_300_8_8_1:
  corpus_size: 50000
  embedding_size: 300
  context_window: 8
  epochs: 8
  min_count: 1
